name: module3_task0

on:
  push:
  
  schedule:
    - cron: '0 0 * * *'
jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
      - name: cloning
        uses: actions/checkout@v2
      - name: make_help
        run: cd module3_task0 && make help
