name: module3_task0

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  module3_task0:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: make_help
        run: cd module3_task0 && make help
