name: module3_task0
run-name: ${{ github.actor }}
on:
  push:
  
  schedule:
    - cron: '0 0 * * *'
jobs:
  module3_task0:
    runs-on: ubuntu-latest
    steps:
      - name: cloning
        uses: actions/checkout@v2
      - name: make_help
        run: cd module3_task0 && make help
