name: module3_task1

on:
  push:
    branches: main
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: cloning
        uses: actions/checkout@v2

      - name: set_up
        run: cd module3_task1 && sudo ./setup.sh

      - name: build
        run: |
          cd module3_task1
          make help
          make build
          make POST_NAME=who-are-we POST_TILTE="who are we" post
          make clean
  
