---
env:
  GH_TOKEN: ${{ github.token }}

name: release_drafter
on:
  push:
    tags: "1.0.1"
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main

jobs:
  release_draf:
    permissions: write-all
    name: release_drafter
    runs-on: ubuntu-18.04

    steps:
      - name: release drafter
        uses: release-drafter/release-drafter@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
